version: '3'

services:
  posts_db:
    image: postgres:10.3-alpine
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: user
      POSTGRES_DB: posts_db
    volumes:
      - ./.dbscripts:/docker-entrypoint-initdb.d
      # mount to host
      # - ./db_volume:/var/lib/postgresql/data
    network_mode: bridge
    container_name: posts_app_db

# volumes:
#   db_volume: